world: Minigames_world
reset-world: true
set-server-texturepack: true
Lasertag:
  mods:
    points: 1
    normal-kill-extra-points: 0
    sniper-kill-extra-points: 1
    headshot-extra-points: 1
    backstab-extra-points: 2
    grenade-kill-extra-points: 1
    pvp-kill-extra-points: 0
    streak-extra-points: 2
    streak-shutdown-extra-points: 2
    multikills-extra-points: 3
    capture-the-flag-points: 15
    minimal-snipe-distance: 25
    minimal-kills-for-streak: 5
    spawnprotection-seconds: 10
    width-addon: 0.0
    height-addon: 0.0
    shoot-through-blocks: false
    highlight-players: false
    grenade-effect-radius: 2.5
    lasergun-cooldown-ticks: 12
    lasergun-multiweapons-cooldown-ticks: 2
    sniper-cooldown-ticks: 100
    shotgun-cooldown-ticks: 40
    grenade-cooldown-ticks: 300
    sniper-ammo: 3
    lasergun-normal-damage: 100
    lasergun-multiweapons-damage: 7
    lasergun-pvp-damage: 8
    shotgun-damage: 11
    sniper-damage: 100
    dagger-damage: 13
    grenade-damage: 15
    headshot-damage-multiplikator: 1.5
    snipe-shot-damage-multiplikator: 1.5
    point-event-first-event-delay-ticks: 1200
    point-event-default-length-ticks: 900
    point-event-next-event-delay-ticks: 900
    point-event-only-points: true
  maps:
    town:
      center:
        x: 396
        y: 22
        z: 212
      area:
        randomspawn: true
        x:
          min: 353
          max: 454
        y:
          min: 4
          max: 31
        z:
          min: 162
          max: 263
      basespawn:
        enabled: false
    laserland:
      center:
        x: 299
        y: 8
        z: -160
      area:
        randomspawn: true
        x:
          min: 250
          max: 347
        y:
          min: 4
          max: 18
        z:
          min: -208
          max: -111
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 252.5
          y: 4
          z: -206.5
          flag:
            x: 260
            y: 4
            z: -198
        blue:
          x: 345.5
          y: 4
          z: -113.5
          flag:
            x: 337
            y: 4
            z: -122
        green:
          x: 252.5
          y: 4
          z: -113.5
          flag:
            x: 260
            y: 4
            z: -122
        yellow:
          x: 345.5
          y: 4
          z: -206.5
          flag:
            x: 337
            y: 4
            z: -199
        protectionradius: 7
    duel:
      center:
        x: 287
        y: 4
        z: -86
      area:
        randomspawn: false
        x:
          min: 259
          max: 317
        y:
          min: 4
          max: 20
        z:
          min: -107
          max: -67
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 260.5
          y: 4
          z: -86.5
          flag:
            x: 271
            y: 4
            z: -87
        blue:
          x: 316.5
          y: 4
          z: -86.5
          flag:
            x: 305
            y: 4
            z: -87
        protectionradius: 5
    bridges:
      center:
        x: 344
        y: 9
        z: -71
      area:
        randomspawn: false
        x:
          min: 321
          max: 366
        y:
          min: 1
          max: 30
        z:
          min: -108
          max: -35
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 338.5
          y: 13
          z: -35.5
          flag:
            x: 339
            y: 10
            z: -42
        blue:
          x: 348.5
          y: 13
          z: -107.5
          flag:
            x: 348
            y: 10
            z: -100
        protectionradius: 3
    skyhigh:
      center:
        x: 746
        y: 101
        z: -410
      area:
        randomspawn: false
        x:
          min: 652
          max: 840
        y:
          min: 74
          max: 116
        z:
          min: -450x
          max: -370
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 814.5
          y: 98
          z: -421.5
          flag:
            x: 800
            y: 87
            z: -427
        blue:
          x: 678.5
          y: 98
          z: -398.5
          flag:
            x: 692
            y: 87
            z: -393
        protectionradius: 7
    big8:
      center:
        x: 298
        y: 4
        z: -263
      area:
        randomspawn: false
        x:
          min: 250
          max: 347
        y:
          min: 4
          max: 24
        z:
          min: -311
          max: -214
      basespawn:
        enabled: true
        capture-the-flag: false
        red:
          x: 295.5
          y: 4
          z: -309.5
        blue:
          x: 302.5
          y: 4
          z: -309.5
        green:
          x: 345.5
          y: 4
          z: -266.5
        yellow:
          x: 345.5
          y: 4
          z: -259.5
        purple:
          x: 302.5
          y: 4
          z: -216.5
        gray:
          x: 295.5
          y: 4
          z: -216.5
        orange:
          x: 252.5
          y: 4
          z: -259.5
        white:
          x: 252.5
          y: 4
          z: -267.5
        protectionradius: 10
    absorbed:
      center:
        x: 276
        y: 4
        z: -366
      area:
        randomspawn: true
        x:
          min: 226
          max: 325
        y:
          min: 4
          max: 24
        z:
          min: -415
          max: -316
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 323.5
          y: 4
          z: -413.5
          flag:
            x: 316
            y: 4
            z: -406
        blue:
          x: 228.5
          y: 4
          z: -318.5
          flag:
            x: 235
            y: 4
            z: -327
        green:
          x: 323.5
          y: 4
          z: -318.5
          flag:
            x: 315
            y: 4
            z: -326
        yellow:
          x: 228.5
          y: 4
          z: -413.5
          flag:
            x: 236
            y: 4
            z: -407
        protectionradius: 10
    darkduel:
      center:
        x: 338
        y: 4
        z: -341
      area:
        randomspawn: false
        x:
          min: 329
          max: 348
        y:
          min: 4
          max: 19
        z:
          min: -365
          max: -316
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 345
          y: 4
          z: -317
          flag:
            x: 340
            y: 4
            z: -329
        blue:
          x: 345
          y: 4
          z: -364
          flag:
            x: 337
            y: 4
            z: -354
        protectionradius: 5
    retro:
      center:
        x: 162
        y: 8
        z: -98
      area:
        randomspawn: true
        x:
          min: 133
          max: 185
        y:
          min: 4
          max: 16
        z:
          min: -122
          max: -70
      basespawn:
        enabled: false
    iceland:
      center:
        x: 98
        y: 4
        z: -158
        block: packed_ice
      area:
        randomspawn: false
        x:
          min: 46
          max: 181
        y:
          min: 4
          max: 34
        z:
          min: -185
          max: -106
      basespawn:
        enabled: true
        capture-the-flag: true
        red:
          x: 150.5
          y: 14
          z: -152,5
          flag:
            x: 143
            y: 9
            z: -153
        blue:
          x: 69.5
          y: 8
          z: -126.5
          flag:
            x: 70
            y: 6
            z: -157
        protectionradius: 4